version: 2.1

jobs:
  build:
    docker:
      - image: ubuntu:22.04
    steps:
      - checkout
      - run:
          name: Get and Update packages
          command: |
            apt-get update && apt-get upgrade
      - run:
          name: Install SFML, CMake, GCC, G++
          command: |
            apt install -y libsfml-dev cmake gcc g++
      - run:
          name: Build the project
          command: |
            mkdir -p build
            cd build
            cmake ..
            make