version: 2.1

jobs:
  build:
    resource_class: small
    docker:
      - image: ubuntu:22.04
    steps:
      - checkout
      - run:
          name: Install Deps
          command: |
            apt-get update && apt-get install -y \
              build-essential \
              cmake \
              git \
              gcc \
              g++ \
              libx11-dev \
              libxrandr-dev \
              libfreetype6-dev \
              libgl1-mesa-dev \
              libudev-dev \
              libopenal-dev \
              libflac-dev \
              libvorbis-dev \
              libjpeg-dev
      - run:
          name: Build and install SFML
          command: |
            git clone --branch 2.5.1 https://github.com/SFML/SFML.git
            mkdir -p SFML/build && cd SFML/build
            cmake .. -DCMAKE_BUILD_TYPE=Release \
               -DCMAKE_INSTALL_PREFIX=/usr
            make -j$(nproc)
            make install
      - run:
          name: Build
          command: |
            mkdir -p build && cd build
            cmake ..
            make
